services:
  gateway:
    build: gateway
    user: root
    ports:
      - 5000:5000/udp
    restart: unless-stopped

  broker:
    image: eclipse-mosquitto:alpine
    user: root
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./broker/config:/mosquitto/config
      - ./broker/data:/mosquitto/data
      - ./broker/log:/mosquitto/log
    restart: unless-stopped

  mqtt-monitor:
    image: nginx:mainline-alpine
    user: root
    ports:
      - 80:80
    volumes:
      - ./mqtt-monitor/html:/usr/share/nginx/html:ro
      - ./mqtt-monitor/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped

  cloud:
    build: cloud
    user: root
    ports:
      # data in
      - 6000:6000/udp
      # dashboard
      - 1880:1880
    volumes:
      # persistent data
      - ./cloud/data:/data
      # protobuf definitions
      - ./shared/protobuf:/protobuf
    restart: unless-stopped
