user root

persistence true
persistence_location /mosquitto/data/

log_dest file /mosquitto/log/mosquitto.log
log_timestamp true
log_dest syslog
log_dest stdout
log_dest topic
log_type all

# mqtt
listener 1883

# websockets
listener 9001
protocol websockets
http_dir /mosquitto/http
