server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # proxy websocket connections to the broker
    # as per: https://nginx.org/en/docs/http/websocket.html
    location = /mqtt {
        proxy_pass http://broker:9001;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
